server:
  port: 8022

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud-demo
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleteStatus