server:
  port: 8022

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

  mail:
    host: smtp.yeah.net
    port: 465
    default-encoding: utf-8
    username: springcloud_mail@yeah.net
    protocol: smtp
    password: PUSEELKXAOWSEDDF
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        ssl:
          enable: true


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleteStatus