config:
  info: TEST

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8098
    gateway:
      routes:
        - id: unique_id1
          uri: https://www.baidu.com
          predicates:
            - Path=/