server:
  port: 8099

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8098
    gateway:
      routes:
        - id: activity_route
          uri: lb://activity
          predicates:
            - Path=/activity/**
        - id: order_route
          uri: lb://order
          predicates:
            - Path=/order/**